spring:
  data:
      elasticsearch:
        clusterName:
        clusterNodes: localhost:9300
        #local: true
        #properties:
        #  http:
        #    enabled: true
        #repositories:
        #  enabled: true